Intergration spec
187jjay187/Blog pull request #9
Opened 2023-03-18 11:33 UTC by 187jjay187

### Project requirements

#### N+1 problem is solved when fetching all posts and their comments for a user.

-  **Before fix**
![Frame 27](https://user-images.githubusercontent.com/90766123/226102445-87aa9d60-303f-4ce5-87d3-64cb5344473e.png)
![Frame 29](https://user-images.githubusercontent.com/90766123/226102456-66484752-fcd1-4bc9-999e-725d9eaf6773.png)

-  **After fix**
![Frame 30](https://user-images.githubusercontent.com/90766123/226102441-f45f7ac9-d617-4586-bb25-d9223ef704b4.png)
![Frame 32](https://user-images.githubusercontent.com/90766123/226102438-a9faec7c-a454-4d5a-b181-c49e21979aa1.png)

#### Integration specs
- Use Capybara to write integration tests for each view in your project.

- User index page:
  - I can see the username of all other users.
  - I can see the profile picture for each user.
  - I can see the number of posts each user has written.
  - When I click on a user, I am redirected to that user's show page.

- user show page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see the user's bio.
  - I can see the user's first 3 posts.
  - I can see a button that lets me view all of a user's posts.
  - When I click a user's post, it redirects me to that post's show page.
  - When I click to see all posts, it redirects me to the user's post's index page.

- User post index page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see a post's title.
  - I can see some of the post's body.
  - I can see the first comments on a post.
  - I can see how many comments a post has.
  - I can see how many likes a post has.
  - I can see a section for pagination if there are more posts than fit on the view.
  - When I click on a post, it redirects me to that post's show page.

- Post show page:
  - I can see the post's title.
  - I can see who wrote the post.
  - I can see how many comments it has.
  - I can see how many likes it has.
  - I can see the post body.
  - I can see the username of each commentor.
  - I can see the comment each commentor left.

2023-03-18 13:08 UTC, KDlamini requested changes
### Hi @187jjay187 🙋‍♀️,  

Great work so far! 💯 
You have outdone yourself by covering all integration specs required for the blog app. 👏🏾 🎊 
There are some issues that you still need to work on to improve your test so that they all pass. You are almost there! 💪🏾 

## Highlights 🌞 

✔️  All required integration specs for the User index and show page, and Post index and show pages are covered
✔️  The N+1 problem with pots is resolved sufficiently
✔️  Great pull request title and description

## Required Changes ♻️
 
 -  Great job implementing all the required tests however most of the tests do pass as illustrated in the image below.

![image](https://user-images.githubusercontent.com/38088818/226107972-050d00b3-d77a-43bb-8adc-05aa7c4f84d9.png)

- Kindly look into it and make sure that you set up your mock data correctly. If by any chance the tests pass on your end, kindly provide a screenshot of the passing tests.

**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-18 13:08 UTC, KDlamini commented on app/controllers/posts_controller.rb
>      @like = current_user.likes.new
Well done solving the N+1 problem with posts!!! 👏🏾 💯

2023-03-18 13:08 UTC, KDlamini commented on spec/intergration/user_index_spec.rb
✔️ Test that asserts you can see the username of all other users.
✔️ Test that asserts you can see the profile picture for each user.
✔️ Test that asserts you can see the number of posts each user has written.
✔️ Test that redirects to the user's show page when you click on a user.

Great job!!! 👍🏾

2023-03-18 13:08 UTC, KDlamini commented on spec/intergration/user_show_spec.rb
✔️ Test that asserts you can see the user's profile picture.
✔️ Test that asserts you can see the user's username.
✔️ Test that asserts you can see the number of posts the user has written.
✔️ Test that asserts you can see the user's bio.
✔️ Test that asserts you can see the user's first 3 posts.
✔️ Test that asserts you can see a button that lets me view all of a user's posts.
✔️ Test that redirects to the post's show page when you click on a user's post.
✔️ Test that redirects to the user's post's index page when you click on a **see all posts**.

Impressive!!! well done!!! 🎆

2023-03-18 13:08 UTC, KDlamini commented on spec/intergration/post_index_spec.rb
✔️ Test that asserts you can see the user's profile picture.
✔️ Test that asserts you can see the user's username.
✔️ Test that asserts you can see the number of posts the user has written.
✔️ Test that asserts you can see a post's title.
✔️ Test that asserts you can see some of the post's body.
✔️ Test that asserts you can see the first comments on a post.
✔️ Test that asserts you can see how many comments a post has.
✔️ Test that asserts you can see how many likes a post has.
✔️ Test that asserts you can see a section for pagination if there are more posts than fit on the view.
✔️ Test that redirects to the post's show page when you click on a post.


Awesome stuff!!! 🚀

2023-03-18 13:08 UTC, KDlamini commented on spec/intergration/post_show_spec.rb
> +  end
[OPTIONAL] kindly fix the description of the test here. Since you are testing that the post has a title, the description should be similar to `should have the post's title` instead of `should have the username of the user`

2023-03-18 13:08 UTC, KDlamini commented on spec/intergration/post_show_spec.rb
✔️ Test that asserts you can see the post's title.
✔️ Test that asserts you can see who wrote the post.
✔️ Test that asserts you can see how many comments it has.
✔️ Test that asserts you can see how many likes it has.
✔️ Test that asserts you can see the post body.
✔️ Test that asserts you can see the username of each commentor.
✔️ Test that asserts you can see the comment each commentor left.

Way to go tiger!!! 💪🏾

2023-03-20 17:17 UTC, 187jjay187 commented
recent changes:
- we've fixed the required changes
- provided a screenshot of the passing test below,

![Frame 34](https://user-images.githubusercontent.com/90766123/226417152-52fdad89-91ce-455c-8cac-4273d2966f02.png)

2023-03-20 17:49 UTC, ShadyShawkat requested changes
## Hi @187jjay187, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-20 17:49 UTC, ShadyShawkat commented on spec/intergration/post_index_spec.rb
> +require 'rails_helper'
- [ ] Good job implementing the tests and avoiding the N+1 problem. However when I tried to run the tests, I got the following result:

![image](https://user-images.githubusercontent.com/62290545/226423846-90d0ed43-50eb-4c5a-89ad-7012aa77a2bb.png)

- Kindly make sure all tests run successfully.

- [HINT] To replicate the following result, you can try to drop the database and recreate it using your migrations. If that doesn't work try to clone the repo. The problem in the tests happens whenever you try to create a record in the database.

![image](https://user-images.githubusercontent.com/62290545/226424522-c9e739dc-fe76-41d4-b55e-30fcb450ac5c.png)

2023-03-23 13:50 UTC, 187jjay187 commented on spec/intergration/post_index_spec.rb
> +require 'rails_helper'
thank you for the code review @ShadyShawkat ,

NOTE TO MY NEW REVIEWER:
I've finally fixed the invisible issues with my test and database as shown in the below screenshot,

**Screenshot:**
![bandicam 2023-03-23 15-41-48-518](https://user-images.githubusercontent.com/90766123/227224241-7c3e75b0-3a18-45b6-b649-ca5637927a86.jpg)

please give me a zoom call if the tests fail on your end so I can show you live evidence of them passing on my side

kind regards
Jay

2023-03-23 13:59 UTC, elisha2kyakpo1 approved these changes
Hi 👋 @187jjay187, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

👍 Great job implementing the changes requested by the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 14:07 UTC, merged